### ISSUE TITLE
How to disable -dev jar?

### ISSUE THREAD

**Issue by marlester-dev** [PaperMC/paperweight-test-plugin#10]
There are 2 two jars, one usual, one dev, I can't find out how to disable dev jar, also with shadowjar it is `-dev-all` jar and `archiveClassifier.set("")` in `shadowJar `doesn't help to remove `-all` suffix.
Is it impossible to disable it?

**Comment by electronicboy** [comment]
You can't disable it, it's the output of the jar task which is needed for
the input to the reobf task

**Comment by jpenilla** [comment]
As cat mentioned you are free to change the output location of the dev jar task yourself. i.e. 
```kotlin
tasks.(jar|shadowJar) {
  destinationDirectory.set(layout.buildDirectory.dir("dev-libs"))
}
```
Hiding the `-dev` artifacts isn't something we're interested in adding to pw or the example.
