### ISSUE TITLE
Fresh template installation causes Read timed out on maven-metadata.xml

### ISSUE THREAD

**Issue by Kirdow** [PaperMC/paperweight-test-plugin#13]
Spent the past 3 hours trying to get paperweight userdev set up with my Groovy Gradle setup. After 2 hours I gave in to converting it to Kotlin DSL. After another hour I decided to just clone this repository and open it in IntelliJ and then branch out from there. Even that fails with the same error.

The steps I've used to set up the repo
```sh
git clone --recursive https://github.com/PaperMC/paperweight-test-plugin testplugin
cd testplugin
gradlew
```
This gets stuck on the following step:
```
<-------------> 0% CONFIGURING [1m]
> root project > Resolve dependencies of :paperweightDevelopmentBundle > maven-metadata.xml
```
Seems like whatever API paperweightDevelopmentBundle is trying to reach doesn't exit?
After about 2 minutes give or take I get a read timeout on the following URL:
```
https://repo.papermc.io/repository/maven-public/io/papermc/paper/dev-bundle/1.20.2-R0.1-SNAPSHOT/maven-metadata.xml
```
The full output is as follows:
```
D:\Root\Programming\Java\testplugin>gradlew

Welcome to Gradle 8.3!

Here are the highlights of this release:
 - Faster Java compilation
 - Reduced memory usage
 - Support for running on Java 20

For more details see https://docs.gradle.org/8.3/release-notes.html


FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'paperweight-test-plugin'.
> Failed to notify project evaluation listener.
   > Could not resolve all files for configuration ':paperweightDevelopmentBundle'.
      > Could not resolve io.papermc.paper:dev-bundle:1.20.2-R0.1-SNAPSHOT.
        Required by:
            project :
         > Could not resolve io.papermc.paper:dev-bundle:1.20.2-R0.1-SNAPSHOT.
            > Unable to load Maven meta-data from https://repo.papermc.io/repository/maven-public/io/papermc/paper/dev-bundle/1.20.2-R0.1-SNAPSHOT/maven-metadata.xml.
               > Could not GET 'https://repo.papermc.io/repository/maven-public/io/papermc/paper/dev-bundle/1.20.2-R0.1-SNAPSHOT/maven-metadata.xml'.
                  > Read timed out

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 1m 34s
```

All the examples, guides and help forums I've seen show people trying to adapt it to their own existing code, and usually get told "just use the template" linking to this repository. But when the repository doesn't work out of the box, it's not much I can do other than creating an issue about it.

## Specs:
**OS:** Windows 11 [Version 10.0.22621.2428]
**Edition:** Windows 11 Pro
**Java version:** 17.0.4.1 2022-08-18 LTS

**Comment by jpenilla** [comment]
from discord announcements
![image](https://github.com/PaperMC/paperweight-test-plugin/assets/11360596/c93231c0-f96c-4826-ba22-488e95ef3a33)
