### ISSUE TITLE
Backgound Java bin stays open

### ISSUE THREAD

**Issue by CodingGuy32** [PaperMC/paperweight-test-plugin#8]
When you run it in debug and stop it via the red stop button in the IntelliJ IDE it will Fail the build and a SE Binary will stay open in the background this will happen everytime you close the debug via the stop button, locking up a bit of memory.
![image](https://user-images.githubusercontent.com/112783204/190874886-c082c745-7557-4e49-89c9-be00e02a1961.png)
and here after opening and stoping a server 3 times.
![image](https://user-images.githubusercontent.com/112783204/190874941-0c8eee68-2a04-4347-ae74-89b92771dc93.png)

**Comment by electronicboy** [comment]
You'd need to see what the thing running actually is, see process explorer or something and grab the full command for those processes, wouldn't be surprised if it wasn't just Gradle being Gradle

**Comment by CodingGuy32** [comment]
It is running the following command:
```"C:\Program Files\Java\jdk-18.0.2.1\bin\java.exe" -XX:MaxMetaspaceSize=256m -XX:+HeapDumpOnOutOfMemoryError -agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=127.0.0.1:50176 --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED --add-opens java.base/java.nio.charset=ALL-UNNAMED --add-opens java.base/java.net=ALL-UNNAMED --add-opens java.base/java.util.concurrent.atomic=ALL-UNNAMED -Xms256m -Xmx512m -Dfile.encoding=windows-1252 -Duser.country=US -Duser.language=en -Duser.variant -cp C:\Users\codin\.gradle\wrapper\dists\gradle-7.4-bin\c0gwcg53nkjbqw7r0h0umtfvt\gradle-7.4\lib\gradle-launcher-7.4.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 7.4```

Just to be sure I am debugging correctly by having a run configuration for gradle with the `runMojangMappedServer` task, right?

**Comment by electronicboy** [comment]
That's the gradle daemon, and, yea, that's the correct run task

This is not an issue with PW, this actually appears to be an issue with IJ: https://youtrack.jetbrains.com/issue/IDEA-242658
